server:
  port: 8080
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 31d
spring:
  application:
    name: electra-server

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: electra_user_server
    password: 2fB3Z7C5Dl1+Z
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle8iDialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  main:
    allow-circular-references: true

  flyway:
    baseline-on-migrate: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  # Set maximum size for HTTP request headers
#server.max-http-request-header-size=512KB
#
#  # Set maximum size for the request body
#spring.servlet.multipart.max-request-size=10MB